### ISSUE TITLE
stid135 - spectrum scan parallel access to multiple adapters not wotking

### ISSUE THREAD

**Issue by deeptho** [deeptho/linux_media#1]
When multiple spectrum scans are started on multiiple adapters, kernel code can crash.
This mya be due to fft hardware only being present on some adapters

**Comment by phkarmur** [comment]
is it fixed by now? or still crashing?

**Comment by deeptho** [comment]
The drivers no longer crash and simultaneous spectra on adapter 0 and 2 seem to work. Same for adapter 0 an 1.
So the issues is probably fixed. It is possible that one scan slows down the other.
