### ISSUE TITLE
incorrect peak estimation

### ISSUE THREAD

**Issue by psyborg55** [deeptho/linux_media#5]
when two transponders are close to each other, neumodvb assumes it is one transponder and estimates incorrect freq/width
example on 10978 V, same issue spotted at 23.5e too
![Screenshot from 2022-06-25 22-59-46](https://user-images.githubusercontent.com/15853469/175790519-7ecf810a-a6c7-46d1-b0cd-c1fb4f3eaf39.png)

proprietary code detect this properly

```
retuning
	FE_GET_EVENT: stat=31, signal=1 carrier=1 viterbi=1 sync=1 timedout=0 locked=1
RESULT: freq=10975.364V Symrate=4599  Stream=-1    MATYPE: 0x0
MODCODE: 0xffffffff
SIG=-26.68dB CNR=7.78dB DVB-S2 8PSK FEC_5_6 INV_OFF PIL_ON  ROLL_35
retuning
	FE_GET_EVENT: stat=31, signal=1 carrier=1 viterbi=1 sync=1 timedout=0 locked=1
RESULT: freq=10981.155V Symrate=4599  Stream=-1    MATYPE: 0x0
MODCODE: 0xffffffff
SIG=-26.68dB CNR=4.77dB DVB-S2 8PSK FEC_5_6 INV_OFF PIL_ON  ROLL_35

```

**Comment by deeptho** [comment]
Peak detection will change again in new versions, so check again. It is a matter of choices also.
