### ISSUE TITLE
Tuner mode

### ISSUE THREAD

**Issue by watercrafting** [deeptho/linux_media#8]
Hello Deepthought,

I would like to receive the data using [vtm_mode](https://github.com/deeptho/linux_media/blob/4631011100d2d31b667ae74dead616ebe9166c3b/drivers/media/dvb-frontends/stid135/stid135_drv.c#L12146) in 6903x or 6909x card but the documentation is not enough. I can call this function but dont know how to get the data and what is the exact output format. If you know how to do that, could you explain or implement a basic example? If it is possible, it can be used as an sdr device or the demodulated bits can be used to implement basic receiver inside software (GNU radio or some other dvbs demodulator source codes leandvb etc.). The card has already these kind of abilities but i would like to learn and implement the receiver for educational purpose. 
If modifications are needed to receive the data from the pcie card, I may do that but need your guidance.

Thanks

**Comment by deeptho** [comment]
vtm mode does not work. This is due to the way the card is wired, so nothing can be 
done about it.
