### ISSUE TITLE
TBSECP3 complies but won't load

### ISSUE THREAD

**Issue by phattyassid** [deeptho/linux_media#9]
Hey Deepthought

thanks for taking up this long term fight on the 6909X and multistreams in Italy ;)

I tried the drivers, compiled with no apparent issues but driver won't load properly

![image](https://github.com/deeptho/linux_media/assets/32552833/abf07ca3-ea1b-45df-ae59-b26f985c3d39)

standard TBS drivers compile and load, but usual issues on 5.0W particularly with Rai 1 HD.

any help is greatly appreciated

Ubuntu 22.04.3 LTS, kernel 5.15.0-78-generic x86_64

pretty much vanilla with not much else going on.

Cheers

Phatty

**Comment by deeptho** [comment]
Looks like a hardware problem or perhaps running old code
